#!/bin/sh
me="$(whoami)"
home=/home/rek
target=/var/www/pkg_gentoo/skylake/pkg/.
# Checking that the script is running as root.
# entering in if case

if [ "$(id -nu)" != "root" ]; then

    # resetting cached credentials
    sudo --reset-timestamp

    # creating a dialog box to enter user password 
    pswd=$(whiptail --title "Authentication" \
    --passwordbox "To run this script, administrative privilege is \
    required. \n[sudo] Password for user $me:" 14 52 3>&2 2>&1 1>&3-)
    
    # executing the script with the password entered by user
    exec sudo --stdin --prompt '' "$0" "$@" <<< "$pswd"

    # if password is wrong it will return the status code 1
    exit 1

# exiting from if condition
fi

rsync -rv --delete /var/cache/binpkgs/. -e "ssh -i $home/.ssh/dream -p 6666" zai@rek3000.tech:$target

ssh -i $home/.ssh/dream zai@rek3000.tech -p 6666 -t "chmod 755 -R $target"
