#!/bin/bash


# Set decoration geometry
berryc border_width       0
berryc inner_border_width 4
berryc title_height       20
berryc edge_gap           38 10 10 10

# Set decoration colors
berryc focus_color         292d3e #292d3e
berryc unfocus_color       292d3e #292d3e
berryc inner_focus_color   92ba92 #92ba92
berryc inner_unfocus_color 525e75 #525e75
berryc text_focus_color    ffffff #ffffff
berryc text_unfocus_color  eeeeee #eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "false"
berryc edge_lock   "true"
berryc set_font    "Iosevka Nerd Font"
berryc decorate_new "true"

killall sxhkd
# sxhkd -c ~/.config/berry/sxhkdrc &
# ~/.config/polybar/launch.sh &
# picom &
